export const CATEGORIES_STATE = {
    SET_CATEGORIES_START: 'category/SET_CATEGORIES_START',
    SET_CATEGORIES_SUCCESS: 'category/SET_CATEGORIES_SUCCESS',
    SET_CATEGORIES_FAILED: 'category/SET_CATEGORIES_FAILED',
};